services:
  - docker:dind

stages:
  - build_deploy

build-and-deploy-job:
  image: docker:19.03.12
  stage: build_deploy
  script:
    - docker build -t "$ACR_NAME"/buutti-webapp-docker-1:latest .
    - docker login "$ACR_NAME" -u "$ACR_USERNAME" -p "$ACR_PASSWORD"
    - docker push "$ACR_NAME"/buutti-webapp-docker-1:latest